apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Values.ballot.serviceName } }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ballot
  template:
    metadata:
      labels:
        app: ballot
    spec:
      containers:
        - name: ballot
          image: { { .Values.ballot.image } }
          ports:
            - containerPort: { { .Values.ballot.targetPort } }
          imagePullPolicy: Always
