apiVersion: v1
kind: Service
metadata:
  labels:
    apps: ballot
  name: { { .Values.ballot.serviceName } }
spec:
  type: NodePort
  selector:
    app: ballot
  ports:
    - name: ballot
      port: { { .Values.ballot.servicePort } }
      targetPort: { { .Values.ballot.targetPort } }
      # nodePort: {{.Values.ballot.nodePort}}
